apiVersion: v1
kind: Service
metadata:
  name: helloworldapi-service
  namespace: helloworldapp
spec:
  selector:
    app: helloworldapi
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP  # Use ClusterIP for port-forwarding
