apiVersion: v1
kind: Pod
metadata:
  name: debug-pvc
spec:
  containers:
    - name: shell
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: my-volume
          mountPath: /data
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
  restartPolicy: Never